<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
        <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div class="jumbotron">
            <h2><?=$this->hello?></h2>
            <p>We guarantee the lowest price in your city of residence, for equal delivery and payment terms.</p>
        </div>
        <div class="row">
            <?php
            foreach ($rowset as $row) {
                ?>
                <div class="col-6 col-sm-6 col-lg-4" style="height:200px;" >
                    <img src="<?php echo $row['image'] ?>" class="img-polaroid" style="max-height:50px">
                    <h4><?php echo $row['brand'] ?></h4>
                    <p><?php echo $row['title'] ?> </p>
                    <p><a class="btn btn-default" 
                          href="<?php echo $this->url('store/default', array('controller' => 'product', 'action' => 'index', 'id' => $row['id'])); ?>" 
                          role="button">View details »</a></p>
                </div><!--/span-->    
            <?php } ?>
        </div><!--/row-->
    </div><!--/span-->
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">    
            <?php
            // view helper
            try {
                if ($user = $this->identity()) {
                    if($this->identity()->enabled === '0'){       
                        
                        $this->flashMessenger()->addMessage('Dear user Your account was blocked by system. Please contact Us for more details.');
                        header( 'Location: ' . $this->url('store/default', array('controller' => 'login', 'action' => 'logout'))) ;                         
                        exit();

                    }
                    ?>

                    <?php
                    echo 'Hello ' . $this->escapeHtml($user->email);
                    ?>                
                    | <a href="<?php echo $this->url('store/default', array('controller' => 'login', 'action' => 'logout')); ?>"><?php echo $this->translate('Logout'); ?></a> <br>
                    <?php if ($user->balance !== '0') {
                        
                    echo     '<p>Current Balance: '.$user->balance.'</p>';
                     } ?>
                    <a href="<?= $this->url('store/default', array('controller' => 'myaccount', 'action' => 'index')) ?>" class="list-group-item">MyAccount</a>     


                    <?php
                } else {
                    ?>
                    <a href="<?= $this->url('store/default', array('controller' => 'login', 'action' => 'index')) ?>" class="list-group-item">Login</a>    
                    <p>
                        <a href="<?php echo $this->url('store/default', array('controller' => 'registration', 'action' => 'index')); ?>"><?php echo $this->translate('Register'); ?></a> |  
                        <a href="<?php echo $this->url('store/default', array('controller' => 'registration', 'action' => 'forgotten-password')); ?>"><?php echo $this->translate('Forgotten Password'); ?></a>
                    </p>
                    <?php
                }
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
        </div>
    </div><!--/span-->
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            Category
            <?php
            foreach ($categories as $cat) {
                echo '<a href="' .
                $this->url('store/default', array('controller' => 'index', 'action' => 'index', 'id' => $cat['id'])) .
                '" class="list-group-item ' . ((isset($activecategory) && $activecategory == $cat['id']) ? 'active' : '') . '">' . $cat['name'] . '</a>';
            }
            ?>
        </div>
    </div><!--/span-->
    
    
    <?php  if ($user = $this->identity()) {
        if ($user->isadmin==1) {          
        ?>
    
     <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">            
            <a href="<?php echo $this->url('store/default', array('controller' => 'admin', 'action' => 'index')); ?>" class="list-group-item"><b>Admin Panel</b></a>
            <a href="<?php echo $this->url('store/default', array('controller' => 'admin', 'action' => 'orders')); ?>" class="list-group-item">Orders</a>            
            <a href="<?php echo $this->url('store/default', array('controller' => 'admin', 'action' => 'users')); ?>" class="list-group-item">Users</a>
            <a href="<?php echo $this->url('store/default', array('controller' => 'admin', 'action' => 'products')); ?>" class="list-group-item">Products</a>
            
        </div>
    </div><!--/span-->
    
    <?php }} ?>
    
</div><!--/row-->