<h1><a href="<?= $this->url('store/default', array('controller' => 'myaccount', 'action' => 'index')) ?>">My Account</a> |  <a href="<?= $this->url('store/default', array('controller' => 'myaccount', 'action' => 'deposit')) ?>">Deposit</a> | History</h1>
<?php
if (sizeof($this->orders) == 0) {
    echo $this->message;
} else {
    echo "<h5>My orders</h5>";
    ?>
<table class="table">
    <tr>
    <th>num</th>
    <th>ID</th>
    <th>Product</th>
    <th>Price</th>
    <th>COUNT</th>
    <!--<td>userid</td>-->
    <th>Time of Order</th>
    <th>Status</th>
        
    
    <tr>
    
    
    <?php     
    foreach ($this->orders as $order)
    {
        echo "<tr>";
        echo "<td>".$order['num']."</td>";
        echo "<td>".$order['id']."</td>";
        echo "<td>".$order['title']."</td>";
        echo "<td>".$order['price']."</td>";
        echo "<td>".$order['count']."</td>";
        //echo "<td>".$order->userid."</td>";
        echo "<td>".$order['dt']."</td>";
        echo "<td>".$order['status']."</td>";
        echo "</tr>";
    }
    ?>
</table>


    <?php
}
?>