<h1>AuthDoctrine index</h1>


<?php echo $this->message; ?>


<hr />


<table>
    <tr>
        <th>id</th>
        <th>email</th>
        <th>password</th>
        <th>firstname</th>
        <th>lastname</th>
        <th>birthdate</th>        
        <th>balance</th>  
        <th>isadmin</th>
        <th>enabled</th>
        
    </tr>
    
    
        <?php foreach ($users as $user){?>
    <tr>
        <td><?php echo $this->escapeHtml($user->get_id());?></td>
        <td><?php echo $this->escapeHtml($user->get_email());?></td>
        <td><?php echo $this->escapeHtml($user->get_password());?></td>
        <td><?php echo $this->escapeHtml($user->get_firstname());?></td>
        <td><?php echo $this->escapeHtml($user->get_lastname());?></td>        
        <td><?php echo $this->escapeHtml($user->get_birthdate());?></td>
        <td><?php echo $this->escapeHtml($user->get_balance());?></td>
        <td><?php echo $this->escapeHtml($user->get_isadmin());?></td>
        <td><?php echo $this->escapeHtml($user->get_enabled());?></td>
        
        
    </tr>
        <?php } ?>
    
    
</table>